# Generated by Django 3.2.7 on 2021-09-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('clave', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro'), ('N', 'Ninguno')], max_length=1)),
            ],
        ),
    ]
